### PR TITLE
Some structuring for files

### PR DESCRIPTION
**Pull request by Fleeym**
This should be good enough as a base file structure.

Endpoints is only for defining route handlers, nothing else. Any complicated logic should be in a separate module.
"types/db" is used for DB entities / models.

### CODE REVIEW

**Comment by matcool** [comment]
imo maybe types/db.rs should be types/models.rs or something

**Comment by Fleeym** [comment]
agreed, will update

**Comment by HJfod** [comment]
People more competent than me contributing 😍 tysm maybe this server won't suck after all

**Comment by Fleeym** [comment]
Updated, I also moved Mod to types/models

**Pull request merged**
